java_library(
    name = "example",
    srcs = ["Cat.java"],
    visibility = ["//visibility:public"]
)

java_library(
    name = "example2",
    srcs = ["Cat2.java"],
    visibility = ["//visibility:public"]
)